name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.20.3'

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install dependencies
      run: yarn install
      working-directory: client-app

    - name: Build with Gradle
      run: |
        export NODE_OPTIONS=--openssl-legacy-provider
        ./gradlew assemble

    - name: Run tests with Gradle
      run: ./gradlew test
